apiVersion: v1
kind: Pod
metadata:
  name: pod-image-policy
spec:
  containers:
  - name: pod-image
    image: nginx
    #imagePullPolicy, one of IfNotPresent, Always(default), Never; defaults to Always
    imagePullPolicy: IfNotPresent